SearchServer: searchServer.cpp searchServer.h KeyWordSearch.cpp seg1.cpp BuildIndex.cpp GAAC.cpp
	g++ -g searchServer.cpp KeyWordSearch.cpp seg1.cpp BuildIndex.cpp GAAC.cpp -o SearchServer

clean:
	rm SearchServer
